[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
reddal = "BEL8p898YNJB5C4mv8azyvbrk6o2f6ANLAhuehr8rBBw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
